# Generated by Django 4.1.7 on 2023-04-03 17:35

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/avatars/', verbose_name='avatar')),
                ('props', models.JSONField(blank=True, null=True, verbose_name='properties')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'gamer',
                'verbose_name_plural': 'gamers',
            },
        ),
        migrations.CreateModel(
            name='GameObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Ready'), (1, 'In progress')], default=0, verbose_name='state')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('coords', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(default=0), size=3, verbose_name='coordinats')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='level')),
                ('props', models.JSONField(blank=True, null=True, verbose_name='props')),
                ('expired_date', models.DateTimeField(blank=True, null=True, verbose_name='expired date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.gamer', verbose_name='owner')),
            ],
            options={
                'verbose_name': 'game object',
                'verbose_name_plural': 'game object',
            },
        ),
    ]
