# Generated by Django 4.1.7 on 2023-04-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameobject',
            name='order_number',
            field=models.PositiveIntegerField(default=0, verbose_name='position'),
        ),
    ]
